"""Type stubs for the compiled ``emsl._emsl`` extension: ``Engine``, ``Batch``, and
``BatchRunner``. Hand-maintained; keep in sync with ``crates/emsl-py/src/lib.rs``.
State and order records come back as plain dicts, typed here as ``dict[str, Any]``.
"""

from typing import Any, Optional

import numpy as np

class Engine:
    def __init__(
        self,
        candles: np.ndarray,
        market: str = ...,
        quote: float = ...,
        fee_taker: float = ...,
        fee_maker: float = ...,
        slippage_bps: float = ...,
        max_fill_fraction: float = ...,
        max_open_orders: int = ...,
        report: bool = ...,
        leverage: float = ...,
        impact: float = ...,
        funding_rate: float = ...,
        funding_interval: int = ...,
    ) -> None: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def data(self) -> np.ndarray: ...
    def reset(self) -> dict[str, Any]: ...
    def step(self) -> dict[str, Any]: ...
    def done(self) -> bool: ...
    def observation(self, lookback: int) -> np.ndarray: ...
    def market_buy(self, size: float) -> int: ...
    def market_sell(self, size: float) -> int: ...
    def limit_buy(self, size: float, price: float) -> Optional[int]: ...
    def limit_sell(self, size: float, price: float) -> Optional[int]: ...
    def stop(self, side: str, size: float, trigger: float) -> Optional[int]: ...
    def order(
        self,
        side: str,
        size: float,
        type: str = ...,
        price: Optional[float] = ...,
        trigger: Optional[float] = ...,
        reduce_only: bool = ...,
        post_only: bool = ...,
        tif: str = ...,
    ) -> Optional[int]: ...
    def close(self) -> Optional[int]: ...
    def cancel(self, order_id: int) -> bool: ...
    def cancel_all(self) -> int: ...
    def qty_from_weight(self, fraction: float) -> float: ...
    def qty_from_quote(self, cash: float) -> float: ...
    def run(self, strategy: Any) -> dict[str, Any]: ...
    def stats(
        self, periods_per_year: float = ..., risk_free: float = ...
    ) -> Optional[dict[str, Any]]: ...
    def equity_curve(self) -> Optional[np.ndarray]: ...
    def trades(self) -> Optional[list[dict[str, Any]]]: ...

class Batch:
    num_envs: int
    def __init__(
        self,
        candles: np.ndarray,
        num_envs: int,
        market: str = ...,
        quote: float = ...,
        fee_taker: float = ...,
        fee_maker: float = ...,
        slippage_bps: float = ...,
        max_fill_fraction: float = ...,
        max_open_orders: int = ...,
        report: bool = ...,
        leverage: float = ...,
        impact: float = ...,
        funding_rate: float = ...,
        funding_interval: int = ...,
        fee_taker_per_env: Optional[np.ndarray] = ...,
        fee_maker_per_env: Optional[np.ndarray] = ...,
        slippage_bps_per_env: Optional[np.ndarray] = ...,
        impact_per_env: Optional[np.ndarray] = ...,
    ) -> None: ...
    def __len__(self) -> int: ...
    def done(self) -> bool: ...
    def reset_all(self) -> list[dict[str, Any]]: ...
    def step_all(self, actions: Optional[np.ndarray] = ...) -> list[dict[str, Any]]: ...
    def advance(self, actions: Optional[np.ndarray] = ...) -> None: ...
    def observe(self, window: int) -> np.ndarray: ...
    def set_features(self, features: np.ndarray) -> None: ...
    def observe_features(self, window: int) -> np.ndarray: ...
    def equities(self) -> np.ndarray: ...
    def dones(self) -> np.ndarray: ...
    def busts(self) -> np.ndarray: ...
    def snapshot(self) -> dict[str, np.ndarray]: ...
    def reset_at_each(self, offsets: np.ndarray) -> None: ...
    def reset_masked(self, mask: np.ndarray, offsets: np.ndarray) -> None: ...

class BatchRunner:
    def __init__(
        self,
        candles: np.ndarray,
        market: str = ...,
        quote: float = ...,
        fee_taker: float = ...,
        fee_maker: float = ...,
        slippage_bps: float = ...,
        max_fill_fraction: float = ...,
        max_open_orders: int = ...,
        leverage: float = ...,
        impact: float = ...,
        funding_rate: float = ...,
        funding_interval: int = ...,
    ) -> None: ...
    def run_all(
        self,
        strategy: str,
        params: np.ndarray,
        periods_per_year: float = ...,
        risk_free: float = ...,
    ) -> dict[str, np.ndarray]: ...
